name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    name: test iOS
    runs-on: macOS-latest
    strategy:
      matrix:
        include:
          - xcode: "15.0"
            ios: "17.0"
    steps:
    - uses: actions/checkout@v1
      
    - name: Run unit tests
      run: xcodebuild test -scheme stockTestAppSwiftUI -project stockTestAppSwiftUI.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' | xcpretty && exit ${PIPESTATUS[0]}
